### ISSUE TITLE
"SampleSceneNoTileMap" get a bake error

### ISSUE THREAD

**Issue by jewis123** [h8man/RedHotSweetPepper#1]
hi there, @h8man 
this is my operation steps:
1.  select NavMesh Object> find NavMeshSurface2D component > change "Use Geometry" property to "Physics Colliders"
2. click bake
3. you will catch a Error: "MissingComponentException: There is no 'CompositeCollider2D' attached to the "Stone" game object, but a script is trying to access it."

Additionally,
I add a Polygon Collider 2D component to the pond object, then, delete all rocks and bake with "Physics Colliders". Strangely, there is no NavMesh Surface appear in the Scene.

My purpose:
Bake a navmesh surface by  using customized collider shape.

So, How to deal with these things?

**Comment by h8man** [comment]
Hi, @jewis123 

Thank you for a feedback. As for ~There is no 'CompositeCollider2D' attached to the "Stone"~, yeah, remove navmeshmodifiers from stones and put navmeshmodifier on walls, cause stones does not have collider, its up in hierarchy used by wall's CompositeCollider2D. 

But BuildNavMesh will not create walkable surface form world bounds, so.. add BoxCollider2D(trigger) and mavmeshmodifier(walkable) to GameFloor and hit bake. Also try set Override Vector (1,1,0)

I will upload sample scene somewhere tomorrow.

**Comment by h8man** [comment]
Added.

* Add Scenes/SampleSceneCollider2d.unity

open it and hit bake, it should work.

**Comment by jewis123** [comment]
great 👍👏
